### PR TITLE
Allow spaces in extra args

### LINKED ISSUE #111: Allow space in extra args
Hi!

It seems, `IFS=' ' read -ra extra_args <<< "$RESTIC_BACKUP_EXTRA_ARGS"` does not respect escaped spaces.

If you print out the entries in `"${extra_args[@]}"` you can see that they are split:
```
--option
sftp.command='ssh\
-F\
/etc/restic/ssh_config\
restic-backup-host\
-s\
sftp'
--exclude-caches
--one-file-system
```
In this example, it leads to -F (option for sftp) to be used as option for restic.

Not sure how to resolve - use `RESTIC_BACKUP_EXTRA_ARGS` somehow like an array? Or allow escapes?

### PR DESCRIPTION
**Pull request by erikw**
Fixes #111

### CODE REVIEW

**Comment by nettnikl** [comment]
I don't have permission to push here.. But i think i might found a way: https://github.com/erikw/restic-automatic-backup-scheduler/pull/113

**Comment by nettnikl** [comment]
Btw, we have to filter out some args... Some args do not work for unlock, like `unknown flag: --exclude-caches`

**Comment by erikw** [comment]
> Btw, we have to filter out some args... Some args do not work for unlock, like `unknown flag: --exclude-caches`

Why does the unlock command need extra args?

**Comment by erikw** [comment]
> I don't have permission to push here.. But i think i might found a way: #113

Oh forgot to clean up the testing, thus the linter job complained as well  :P

The PR is updated, please try it again :)

**Comment by nettnikl** [comment]
> I'd say this is such a special case that it's bloating the code too much, to solve one persons specific setup. See https://github.com/erikw/restic-automatic-backup-scheduler#project-scope I'd recommend you to keep a personal fork that adds extra args to the unlock command as well for your specific setup :)

Okay, will keep my fork updated then :+1: 

Had trouble with the given changes still, though: `unknown flag: --one-file-system --exclude-caches --option sftp.command`
Still same issue as described here: https://github.com/erikw/restic-automatic-backup-scheduler/issues/111#issuecomment-1556167426

**Comment by erikw** [comment]
> Had trouble with the given changes still, though: `unknown flag: --one-file-system --exclude-caches --option sftp.command`
> Still same issue as described here: [#111 (comment)](https://github.com/erikw/restic-automatic-backup-scheduler/issues/111#issuecomment-1556167426)

Ha, interesting! With my debug printing, it looks like your command was showing properly and would work. I tried to stay by the simpler solution. 

I applied to solution you demonstrated in #113 to this PR now.

Does it work now? :)

**Comment by nettnikl** [comment]
Yeah, should be fine, it looks to be similar to my earlier proposals (minus my `restic unlock` mod, plus docu), so i'm happy with it!

**Comment by erikw** [comment]
> it looks to be similar to my earlier proposals

Indeed, I copied it! :)

**Pull request merged**
